name: Build Lost 0.8.0 APK
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'v0.8.0'

      - name: set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      # Шаг с chmod +x мы полностью удалили, так как файла gradlew нет

      - name: Build APK with global Gradle
        # Вместо ./gradlew пишем просто gradle (используем системный сборщик сервера)
        run: gradle assembleDebug --no-daemon --stacktrace
        continue-on-error: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pocket-code-v0.8.0-debug
          path: "**/*.apk"
