name: Build Lost 0.8.0 APK
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'v0.8.0'

      - name: set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle 2.14.1
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '2.14.1'

      - name: Build Pure APK
        # Насильно вызываем сборку именно подмодуля приложения (:catroid), 
        # отключая любые проверки, тесты и линтеры (-x test -x lint), чтобы ничего не падало
        run: gradle :catroid:assembleDebug --no-daemon -x test -x lint
        continue-on-error: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pocket-code-v0.8.0-debug
          path: "**/*.apk"
